version: "3.9"  # optional since v1.27.0
services:
  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=application
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  test-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=application
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - 5434:5432