version: "3.9"  # optional since v1.27.0
services:
  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=application
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  test-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker_test
      - POSTGRES_PASSWORD=docker_test
      - POSTGRES_DB=application_test
    volumes:
      - ./database-data_test:/var/lib/postgresql/data
    ports:
      - 5433:5432
  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass yourpassword
    volumes: 
      - ./cache:/data
volumes:
  cache:
    driver: local